# Generated by Django 3.0.2 on 2020-03-01 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='test',
            field=models.CharField(choices=[('', '')], default='', max_length=55),
        ),
    ]
