# Generated by Django 3.0.2 on 2020-03-01 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='test',
        ),
    ]
