# Generated by Django 3.0.2 on 2020-06-25 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('brand', '0001_initial'),
        ('listings', '0003_remove_listing_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='car_brand',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='brand.Brand'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='car_user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Accounts'),
            preserve_default=False,
        ),
    ]
