# Generated by Django 3.0.2 on 2020-06-25 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('listings', '0004_auto_20200625_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='car_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Accounts'),
        ),
    ]
