# Generated by Django 3.0.2 on 2020-03-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0002_auto_20200301_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='test',
            field=models.CharField(choices=[('', '')], default='', max_length=55),
        ),
    ]
