# Generated by Django 3.0.2 on 2020-03-01 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0003_realtor_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realtor',
            name='test',
        ),
        migrations.AddField(
            model_name='realtor',
            name='aaa',
            field=models.TextField(default=''),
        ),
    ]
