# Generated by Django 3.0.2 on 2020-06-25 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0004_auto_20200301_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realtor',
            name='aaa',
        ),
    ]
