# Generated by Django 3.0.2 on 2020-06-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date Joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Last Login')),
                ('active', models.BooleanField(default=True)),
                ('admin', models.BooleanField(default=False)),
                ('staff', models.BooleanField(default=False)),
                ('customer', models.BooleanField(default=False)),
                ('realtor', models.BooleanField(default=False)),
                ('user_rate', models.IntegerField(blank=True, null=True)),
                ('user_no_posts', models.IntegerField(blank=True, null=True)),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('lase_name', models.CharField(max_length=60, verbose_name='Lase Name')),
                ('punishments', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
