# Generated by Django 3.0.2 on 2020-06-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('br_name', models.CharField(max_length=20)),
                ('br_cars_inside_company', models.IntegerField()),
                ('br_description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
